### ISSUE TITLE
Incorporate “imposed” name constraints from NSS

### ISSUE THREAD

**Issue by briansmith** [rustls/webpki-roots#7]
See https://hg.mozilla.org/projects/nss/rev/1fefea6530e1.

AFAICT these kinds of name constraints aren't applied to roots included in this set. The webpki crate provides a way to add the imposed constraints but currently the webpki-roots build script doesn't know how to find the imposed constraints. It seems like this might have to be done by manual intervention?

**Comment by ctz** [comment]
This is done, such that the new Turkish root has its name constraint applied.

However, I can't actually find a site which uses this root to test. The official test server doesn't support reasonably modern TLS; others do but send incomplete certificate chains.

**Comment by briansmith** [comment]
There are two problems with testing: Finding a cert chain that should succeed, and finding one that should fail.

To find one that should succeed, I believe you can just use Google Chrome or MSIE or anything but Firefox to connect to the test server, and then export the chain that that browser constructs. (It will use AIA fetching to complete the chain.) And/or find one in CT logs.

To find one that should fail, I think the best shot would be to search the CT logs.

**Comment by ctz** [comment]
> To find one that should succeed ...

Good point, thanks. I did that and put the result into a test; which fails. Though it passes if I take the constraint off the relevant root. More investigation needed, so reopening this.

From CT it appears nothing has been issued outside the name constraints.

**Comment by briansmith** [comment]
I probably made the name constraint implementation in webpki too strict, and/or broke it, when I simplified it. I will look at it.

**Comment by ctz** [comment]
The test is here 65282d9f07f46d9f272c82034811f9155920844b if that's useful.

**Comment by est31** [comment]
@ctz none of the certs added by the commit you mentioned has a name constraints extension

**Comment by est31** [comment]
[root](https://lapo.it/asn1js/#MIIEYzCCA0ugAwIBAgIBATANBgkqhkiG9w0BAQsFADCB0jELMAkGA1UEBhMCVFIxGDAWBgNVBAcTD0dlYnplIC0gS29jYWVsaTFCMEAGA1UEChM5VHVya2l5ZSBCaWxpbXNlbCB2ZSBUZWtub2xvamlrIEFyYXN0aXJtYSBLdXJ1bXUgLSBUVUJJVEFLMS0wKwYDVQQLEyRLYW11IFNlcnRpZmlrYXN5b24gTWVya2V6aSAtIEthbXUgU00xNjA0BgNVBAMTLVRVQklUQUsgS2FtdSBTTSBTU0wgS29rIFNlcnRpZmlrYXNpIC0gU3VydW0gMTAeFw0xMzExMjUwODI1NTVaFw00MzEwMjUwODI1NTVaMIHSMQswCQYDVQQGEwJUUjEYMBYGA1UEBxMPR2ViemUgLSBLb2NhZWxpMUIwQAYDVQQKEzlUdXJraXllIEJpbGltc2VsIHZlIFRla25vbG9qaWsgQXJhc3Rpcm1hIEt1cnVtdSAtIFRVQklUQUsxLTArBgNVBAsTJEthbXUgU2VydGlmaWthc3lvbiBNZXJrZXppIC0gS2FtdSBTTTE2MDQGA1UEAxMtVFVCSVRBSyBLYW11IFNNIFNTTCBLb2sgU2VydGlmaWthc2kgLSBTdXJ1bSAxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr3UwM6q7a9OZLBI3hNmNe5eA027n_5tQlT6QlVZC1xl8JoSNkvoBHToP4mQ4t4y86Ij5iySrLqP1N-RAjhgleYN1Hzv_bKjFxlb4tO2KRKOrbEz8HdDc72i9z-SqzvBV96I01INrN3wcwv61A-xXzry0tcXtAA9TNypN9E8Mg_uGz8v-jE69h_mniyFXnHrfA2eJLJ2XYacQuFWQfw4tJzh03-f92k4S400VIgLI4OD8D62K18lUUMw7D8oWgITQUVbDjlZ_iSIzL-aFCr2lqBs23tPcLG07xxO9WSMs5uWk99gL7eqQQESolbuT1dCANLZGeA4fAJNG4e7p-exPFwIDAQABo0IwQDAdBgNVHQ4EFgQUZT_HiobGPN08VFw1-DrtUgxHV8gwDgYDVR0PAQH_BAQDAgEGMA8GA1UdEwEB_wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBACo_4fEyjq7hmFxLXs9rHmoJ0iKpEsdeV31zVmSAhHqT5Am5EM2fKifhAHe-SMg1qIGf5LgsyX8OsNJLN13qudULXjS99HMpw-0mFZx-CFOKWI3QSyjfwbPfIPP54-M638yclNhOT8NrF7f3cuitZjO1JVOr4PhMqZ398g26rrnZqsZr-ZO7rqu4lzwDGrpDxpa5RXI4s6ehlj2Re37AIVNMh-3yC1SVUZPVIqUNivGTDj5UDrDYyU7c8jEyVupk-eq1nRZmQnLzf9OxMUP8pI4X8W0jq5Rm-K37DwhuJi1_FwcJsoz7UMCflo3Ptv0AnVoUmr8CRPXBwp8iXqIPoeM)

[intermediary](https://lapo.it/asn1js/#MIIGcjCCBVqgAwIBAgIBKTANBgkqhkiG9w0BAQsFADCB0jELMAkGA1UEBhMCVFIxGDAWBgNVBAcTD0dlYnplIC0gS29jYWVsaTFCMEAGA1UEChM5VHVya2l5ZSBCaWxpbXNlbCB2ZSBUZWtub2xvamlrIEFyYXN0aXJtYSBLdXJ1bXUgLSBUVUJJVEFLMS0wKwYDVQQLEyRLYW11IFNlcnRpZmlrYXN5b24gTWVya2V6aSAtIEthbXUgU00xNjA0BgNVBAMTLVRVQklUQUsgS2FtdSBTTSBTU0wgS29rIFNlcnRpZmlrYXNpIC0gU3VydW0gMTAeFw0xNTA1MTQxMzMyMjdaFw0yNTA1MTExMzMyMjdaMIHfMQswCQYDVQQGEwJUUjEYMBYGA1UEBwwPR2ViemUgLSBLb2NhZWxpMUIwQAYDVQQKDDlUdXJraXllIEJpbGltc2VsIHZlIFRla25vbG9qaWsgQXJhc3Rpcm1hIEt1cnVtdSAtIFRVQklUQUsxLTArBgNVBAsMJEthbXUgU2VydGlmaWthc3lvbiBNZXJrZXppIC0gS2FtdSBTTTFDMEEGA1UEAww6VFVCSVRBSyBLYW11IFNNIFNTTCBTZXJ0aWZpa2EgSGl6bWV0IFNhZ2xheWljaXNpIC0gU3VydW0gMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL2_oOCsOs5RrqU5xA8qZuHMy2hujUGeLeY4qcoICE-KuS5bLvexKrmtkZS_wCrWxqOeOriNlC1F7lia4yHMJp39vG8v6zgaixeyyCxeiIt3AFHziOx7xfOIqLS5Ygbm-FyEwSXOLA-wjg7FHoJ50INzm_Y-IeN96jYBA__1H9b76KFIsGtWn1CpMzglSPqKusmoir4l3NzQEDYf68xmFzB_VDbYPd90j6bzx5T_8Y9RR0CW_m7e6DCfMtBCjCQkum6E9ReSfgGizcDzSGbQQFxVBBYXi_hgBsP6RySuZNB9Pgru6hSxskBpMPoppgeVBBb_-EdSDTbRqth5fVsElEMCAwEAAaOCAkIwggI-MB8GA1UdIwQYMBaAFGU_x4qGxjzdPFRcNfg67VIMR1fIMB0GA1UdDgQWBBT2NTUXri77t333dheKZWTrZ3pAqzAOBgNVHQ8BAf8EBAMCAQYwggEbBgNVHSAEggESMIIBDjCCAQoGBFUdIAAwggEAMCsGCCsGAQUFBwIBFh9odHRwOi8vZGVwby5rYW11c20uZ292LnRyL2lsa2UvMIHQBggrBgEFBQcCAjCBwx6BwABCAHUAIABzAGUAcgB0AGkAZgBpAGsAYQAgAGkAbABlACAAaQBsAGcAaQBsAGkAIABTAGUAcgB0AGkAZgBpAGsAYQAgAEkAbABrAGUAbABlAHIAaQBuAGkAIABvAGsAdQBtAGEAawAgAGkA5wBpAG4AIABiAGUAbABpAHIAdABpAGwAZQBuACAAdwBlAGIAIABzAGkAdABlAHMAaQBuAGkAIAB6AGkAeQBhAHIAZQB0ACAAZQBkAGkAbgBpAHoALjASBgNVHRMBAf8ECDAGAQH_AgEAMD8GA1UdHwQ4MDYwNKAyoDCGLmh0dHA6Ly9kZXBvLmthbXVzbS5nb3YudHIvc3NsL1NTTEtPS1NJTC5TMS5jcmwweAYIKwYBBQUHAQEEbDBqMDkGCCsGAQUFBzAChi1odHRwOi8vZGVwby5rYW11c20uZ292LnRyL3NzbC9TU0xLT0tTTS5TMS5jZXIwLQYIKwYBBQUHMAGGIWh0dHA6Ly9vY3Nwc3Nsa29rczEua2FtdXNtLmdvdi50cjANBgkqhkiG9w0BAQsFAAOCAQEArDB3_x-K_9STX_RcVKRPO5mv03Uli-7tiZk51ipo5ItpPpSUbjHrXy4Ewtc0Rra_zFFHH7AEFxAUU3SL1M3sZcmTMSvSfVhbNW6kZUE1VRY0ZhnBZe0pY1eAOXxj03FTqEGrushFywTqgrFZdLuQ_4SfY8_8afyI5StH6nAOiMgyDNppl93XIS0U6zz1iCOwb6ToBYTAIK-BFP04PMA2wqc7ulgQH0uu8pPPzkdRostMaxwtSreedA-cCGExK5OyA_BX0VtjlEUxJcmmoY3fXO6z1q0_G2PWtvlsBZB1kQkWpUgaTcoiWUO_8qMZRgLmY-jlCktjqp7mkrwusrzEHg)

[subject](https://lapo.it/asn1js/#MIIGbTCCBVWgAwIBAgIKANLnaZiNJWvWfjANBgkqhkiG9w0BAQsFADCB3zELMAkGA1UEBhMCVFIxGDAWBgNVBAcMD0dlYnplIC0gS29jYWVsaTFCMEAGA1UECgw5VHVya2l5ZSBCaWxpbXNlbCB2ZSBUZWtub2xvamlrIEFyYXN0aXJtYSBLdXJ1bXUgLSBUVUJJVEFLMS0wKwYDVQQLDCRLYW11IFNlcnRpZmlrYXN5b24gTWVya2V6aSAtIEthbXUgU00xQzBBBgNVBAMMOlRVQklUQUsgS2FtdSBTTSBTU0wgU2VydGlmaWthIEhpem1ldCBTYWdsYXlpY2lzaSAtIFN1cnVtIDEwHhcNMTcwMzA3MDU0NDA3WhcNMjAwMzA2MDU0NDA3WjB0MQswCQYDVQQGEwJUUjEQMA4GA1UECAwHVFVSS0lZRTEQMA4GA1UEBwwHS09DQUVMSTEQMA4GA1UECgwHVFVCSVRBSzEPMA0GA1UECwwGS2FtdVNNMR4wHAYDVQQDDBV0ZXN0c3NsLmthbXVzbS5nb3YudHIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDF2tpJYQ7uNjH5M9MYRBVgNV5psEc9zwyuuVUCzfB2uUDj0_VyxdjCyNeO8A308D1LCV2t1Skw3m5vKMcBznyTShSwJ_O9S1gxTZHK1Fh9vh_yzD_pIDes5EhaKl6UjONYQArAPe69F_wUGyJlp65Jln1Zg8YsO6pBnkx7wlhkKZy5RJ4pDHkUad_DU4xiGYm6vUjVjCRV79fj-cmiHiUnnwSpBO9QIMSQNOSBTTlsp7iP_58nPgob_hxAt1iMm_WdJH1hN7NOWjQhNtjno0yTKtRI0_htJzCoXC0qTZukplUa99eixZBdkxvv_seRfbow2Ou_cecqAQ2vTRjEGmzVAgMBAAGjggKTMIICjzAfBgNVHSMEGDAWgBT2NTUXri77t333dheKZWTrZ3pAqzAdBgNVHQ4EFgQUFsBOMIPV_CW5Jb394yryIAMwCYAwDgYDVR0PAQH_BAQDAgWgMIIBPQYDVR0gBIIBNDCCATAwggEiBgtghhgBAgEBBQcBAzCCAREwKgYIKwYBBQUHAgEWHmh0dHA6Ly9kZXBvLmthbXVzbS5nb3YudHIvaWxrZTCB4gYIKwYBBQUHAgIwgdUegdIAQgB1ACAAcwBlAHIAdABpAGYAaQBrAGEAIABpAGwAZQAgAGkAbABnAGkAbABpACAAcwBlAHIAdABpAGYAaQBrAGEAIAB1AHkAZwB1AGwAYQBtAGEAIABlAHMAYQBzAGwAYQByATEAbgExACAAbwBrAHUAbQBhAGsAIABpAOcAaQBuACAAYgBlAGwAaQByAHQAaQBsAGUAbgAgAHcAZQBiACAAcwBpAHQAZQBzAGkAbgBpACAAegBpAHkAYQByAGUAdAAgAGUAZABpAG4AaQB6AC4wCAYGZ4EMAQICMAkGA1UdEwQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9kZXBvLmthbXVzbS5nb3YudHIvc3NsL1NTTFNJTC5TMS5jcmwwcgYIKwYBBQUHAQEEZjBkMDYGCCsGAQUFBzAChipodHRwOi8vZGVwby5rYW11c20uZ292LnRyL3NzbC9TU0xTTS5TMS5jZXIwKgYIKwYBBQUHMAGGHmh0dHA6Ly9vY3Nwc3NsczEua2FtdXNtLmdvdi50cjAgBgNVHREEGTAXghV0ZXN0c3NsLmthbXVzbS5nb3YudHIwDQYJKoZIhvcNAQELBQADggEBAFfXPMdkjLAVE60BCYZsZ6z3SPVref3T9UoHtmFfc-qrmy2xEr-zt0yFC_LEZfOQyEeX7LcTHxvDt3bgdJ0ed7s5IKekTXeMFAbE8j_QtDnuRw5STmF5rqgRue3GTNa7sL2XjkL3dom7Bh3THe_JhdEnD0MoJeByhcJng58vjGmsqWPTh_oFWBrDdagXHaydkguQ5nhVYCixbrbm8OT4XJ3eZupattHmxvD5qMBAeGMu9iu4tQvkHMO7xytjBW0qGPgOamccusFgokgO0ALwPa0lbGRWdxHrPgIu5N33wPqTi1kc5sLSLx168A5NYySQP7Csf16131y_PzCp0uPzU9M)

No name constraints extensions. Only certificate policy extensions, but those aren't the same.

**Comment by est31** [comment]
Oh nevermind, I've misunderstood. The name constraints are imposed from the outside.

**Comment by cpu** [comment]
As of https://github.com/rustls/webpki-roots/pull/41 we're including the imposed name constraints from CCADB automatically. There may be future work required to adjust to upstream data format changes but the one root with imposed name constraints has a correctly generated webpki encoded name constraints value.
