### ISSUE TITLE
webpki-roots v0.26.4+ published with MPL-2.0 license but contains Apache-2.0 and MIT license texts

### ISSUE THREAD

**Issue by decathorpe** [rustls/webpki-roots#79]
The webpki-roots crate has an MPL-2.0 license but now ships Apache-2.0 and MIT license texts. It looks like this was unintentional? Please restore the MPL-2.0 license text and remove the LICENSE-APACHE and LICENSE-MIT symlinks from the webpki-roots workspace member.

It looks like this PR which added symlinks for license texts is the cause:
https://github.com/rustls/webpki-roots/pull/75

**Comment by cpu** [comment]
:facepalm: Thank you for catching this. You're right, I messed this up in https://github.com/rustls/webpki-roots/pull/75/commits/6bcc0ec2bcfbf675b27ad8ec98524077883d2147. Fixing in #80

**Comment by decathorpe** [comment]
Thanks for the quick fix! 🚀

**Comment by djc** [comment]
> it looks like this issue is still here [@ctz](https://github.com/ctz) [@djc](https://github.com/djc)

What exactly are you observing? Please make a new issue with the complete context.

**Comment by andrewbanchich** [comment]
Ah, my mistake. I saw all three license files in the root of the repo but didn't realize this is a workspace.
